### ISSUE TITLE
mouse scroll doesn't work on ubuntu 14.04

### ISSUE THREAD

**Issue by syswow** [coolwanglu/neovim.as#22]
Hi, 
OS: Ubuntu 14.04 x64. 
1. neovim.as open a file
2. try use mouse to scroll. (it doesn't work)
3.( but it works on Nerdtree. )

**Comment by coolwanglu** [comment]
Has this issue been solved by #23 ?

**Comment by syswow** [comment]
No, #23 solve the bg_color, but the mouse scroll problem remains unresolved.

**Comment by timshannon** [comment]
Yeah I'm seeing the same.  It looks to be a focusing issue with splits. If you open up a vsplit and scroll up and down on the right split, it'll work for a few scrolls, then the scroll focus jumps back to the left hand split.

**Comment by coolwanglu** [comment]
#53 is recently merged. I wonder if it helps.

**Comment by timshannon** [comment]
Nope, that's the one I was on and had the behavior described above.
